            - name: Databricks Create Job
  # You may pin to the exact commit or the version.
  # uses: sohanmanju/databricks-create-job@e8fd581f90bf9bc63717110811734a9def031dc2
  uses: sohanmanju/databricks-create-job@v0.2.3
  with:
    # Folder path where the input files are located
    input-folder: 
    # Job Template file name without extension
    template-file: 
    # File which contains the inputs that need to be substituted in the jobs template file
    input-file: 
    # Databricks Access Token to deploy the jobs in your account
    databricks-token: 
    # Databricks Host URL
    databricks-host: 
    
name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
